[package]
name = "tf2-config-manager"
version = "0.1.0"
edition = "2021"

[features]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "4.2.5"
serde = {vesrion = "1.0.162", features=["derive"]}
serde_json = "1.0.96"
